//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.1022
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap frmAbout_background {
            get {
                object obj = ResourceManager.GetObject("frmAbout_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmChildBase_closebox {
            get {
                object obj = ResourceManager.GetObject("frmChildBase_closebox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmChildBase_maxbox {
            get {
                object obj = ResourceManager.GetObject("frmChildBase_maxbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmChildBase_minbox {
            get {
                object obj = ResourceManager.GetObject("frmChildBase_minbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmChildBase_MouseMove_closebox {
            get {
                object obj = ResourceManager.GetObject("frmChildBase_MouseMove_closebox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmChildBase_MouseMove_maxbox {
            get {
                object obj = ResourceManager.GetObject("frmChildBase_MouseMove_maxbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmChildBase_MouseMove_minbox {
            get {
                object obj = ResourceManager.GetObject("frmChildBase_MouseMove_minbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_menubar_menuItem_exportCSV {
            get {
                object obj = ResourceManager.GetObject("frmMain_menubar_menuItem_exportCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_menubar_menuItem_exportJSON {
            get {
                object obj = ResourceManager.GetObject("frmMain_menubar_menuItem_exportJSON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_menubar_menuItem_exportProfile {
            get {
                object obj = ResourceManager.GetObject("frmMain_menubar_menuItem_exportProfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_menubar_menuItem_exportReport {
            get {
                object obj = ResourceManager.GetObject("frmMain_menubar_menuItem_exportReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_menubar_menuItem_importProfile {
            get {
                object obj = ResourceManager.GetObject("frmMain_menubar_menuItem_importProfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_toolbar_toolItem_console {
            get {
                object obj = ResourceManager.GetObject("frmMain_toolbar_toolItem_console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_toolbar_toolItem_cursor {
            get {
                object obj = ResourceManager.GetObject("frmMain_toolbar_toolItem_cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_toolbar_toolItem_logger {
            get {
                object obj = ResourceManager.GetObject("frmMain_toolbar_toolItem_logger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_toolbar_toolItem_productManager {
            get {
                object obj = ResourceManager.GetObject("frmMain_toolbar_toolItem_productManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_toolbar_toolItem_quote {
            get {
                object obj = ResourceManager.GetObject("frmMain_toolbar_toolItem_quote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_toolbar_toolItem_quoteManager {
            get {
                object obj = ResourceManager.GetObject("frmMain_toolbar_toolItem_quoteManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_toolbar_toolItem_script {
            get {
                object obj = ResourceManager.GetObject("frmMain_toolbar_toolItem_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmProductManager_toolbar_toolItem_All {
            get {
                object obj = ResourceManager.GetObject("frmProductManager_toolbar_toolItem_All", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmProductManager_toolbar_toolItem_Basic {
            get {
                object obj = ResourceManager.GetObject("frmProductManager_toolbar_toolItem_Basic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmProductManager_toolbar_toolItem_Create {
            get {
                object obj = ResourceManager.GetObject("frmProductManager_toolbar_toolItem_Create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmProductManager_toolbar_toolItem_Custom {
            get {
                object obj = ResourceManager.GetObject("frmProductManager_toolbar_toolItem_Custom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmProductManager_toolbar_toolItem_Delete {
            get {
                object obj = ResourceManager.GetObject("frmProductManager_toolbar_toolItem_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmProductManager_toolbar_toolItem_Modify {
            get {
                object obj = ResourceManager.GetObject("frmProductManager_toolbar_toolItem_Modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmProductManager_toolbar_toolItem_Save {
            get {
                object obj = ResourceManager.GetObject("frmProductManager_toolbar_toolItem_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmScriptParameters_dataGrid_cell_keyboard {
            get {
                object obj = ResourceManager.GetObject("frmScriptParameters_dataGrid_cell_keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmScriptParameters_toolbar_toolItem_Create {
            get {
                object obj = ResourceManager.GetObject("frmScriptParameters_toolbar_toolItem_Create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmScriptParameters_toolbar_toolItem_Delete {
            get {
                object obj = ResourceManager.GetObject("frmScriptParameters_toolbar_toolItem_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmWelcome_background {
            get {
                object obj = ResourceManager.GetObject("frmWelcome_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
